Emisní koláč EU
faktaoklimatu/web-cz pull request #1073
Opened 2022-07-08 12:46 UTC by katkolouchova

2022-07-13 15:01 UTC, jankrcal commented
Kouknu na to zítra ráno ve vlaku.

2022-07-14 11:54 UTC, jankrcal requested changes
Vypadá dobře.

Jediná věc na diskuzi: přišlo by mi fajn v grafice i doprovodném textu více zdůraznit EU-28. Brexit už byl dávno a lidi si nemusí pamatovat, že v roce 2019 ještě GB byla v EU. Co myslíš?

2022-07-14 11:57 UTC, jankrcal commented
Pár neblokujících komentářů:
- přišlo by mi fajn časem sloučit s datasetem https://docs.google.com/spreadsheets/d/1KNL5d1CwLsLc8INquN7z5ABdr52APEsDjEsUcYGh_Mk/edit#gid=979818322 a mít tak všechny EU grafiky postavené na stejných datech
- Kdybys to neměla hotový, navrhl bych smazat ty procenta a přepočty na osobu v doprovodném textu. Je to hrozně pracný na aktualizaci a za mě nepřináší takovou hodnotu. Můžeme z těchto všech grafik odstranit příště, až je budeme aktualizovat.
- Proč se upravují čísla v doprovodném textu vývoj EU? Byly prostě špatně?

2022-07-14 13:09 UTC, katkolouchova commented
> Pár neblokujících komentářů:
> 
>     * přišlo by mi fajn časem sloučit s datasetem https://docs.google.com/spreadsheets/d/1KNL5d1CwLsLc8INquN7z5ABdr52APEsDjEsUcYGh_Mk/edit#gid=979818322 a mít tak všechny EU grafiky postavené na stejných datech
> 
>     * Kdybys to neměla hotový, navrhl bych smazat ty procenta a přepočty na osobu v doprovodném textu. Je to hrozně pracný na aktualizaci a za mě nepřináší takovou hodnotu. Můžeme z těchto všech grafik odstranit příště, až je budeme aktualizovat.
> 
>     * Proč se upravují čísla v doprovodném textu vývoj EU? Byly prostě špatně?

Souhlasím, že sloučení by bylo fajn – asi až se budou data aktualizovat, založím na to issue a někdy se do toho můžeme pustit.

Ano, aktualizace čísel zabrala hodně času, tak to příště už dělat nemusíme :)

Čísla jsem upravila kvůli tomu, že se data mírně změnila v některých sektorech, šlo o jednotky, nic velkého, ale i tak jsem to upravila. Pravděpodobně v Eurostatu data mírně aktualizovali i zpětně. Ale taky mi to zabralo extra čas – v tomto jsou ty statické vizualizace a datasety trochu nešikovné, i když jsem si grafiku přegenerovala v Rku, stejně pak bylo potřeba změny manuálně převést :)

2022-07-14 13:31 UTC, jankrcal approved these changes
Ano, prosím přidej poznámku o EU-27.

Až to bude, můžeš udělat merge (dataset jsem zveřejnil).

2022-07-14 14:19 UTC, merged