Mixy výroby elektřiny v EU a VB
faktaoklimatu/web-cz pull request #1147
Opened 2023-01-22 16:42 UTC by katkolouchova

2023-02-24 13:42 UTC, katkolouchova commented
Může jít ven.

2023-02-27 08:02 UTC, jankrcal commented
Kromě drobných komentářů a návrhů mám 2 high-level věci:
 - Proč zveřejňujeme grafiky nad daty z roku 2021, když už jsou venku data za rok 2022? Je za tím nějaká strategická úvaha? Je s tím moc práce to přegenerovat?
 - Prosím smaž z toho PR věci, které se nepoužívají (`assets-local/figures/elektrina-mix-eu/cs-elektrina-mix-eu-cze.svg`, `includes-local/elektrina-mix-eu/country-summary.html`, změny v `assets-local/local.scss`.

2023-02-27 08:03 UTC, jankrcal requested changes

2023-02-27 08:47 UTC, mgrabovsky commented on collections/_infographics/energetika/elektrina-mix-eu.md
> +**Hlavním zdrojem elektřiny Česka je stále uhlí**, které má skončit v roce 2033[^programove-prohlaseni]. Dalším významným producentem elektřiny jsou **čtyři bloky v jaderné elektrárně Dukovany a dva
Navrhoval bych spíš „výstavbu“. „Dostavba“ mi evokuje, že to bylo od začátku v plánu, jen do toho něco vlezlo, a proto se to zatím nestihlo. Tak to podle mého chápání situace ale není.

2023-02-27 09:00 UTC, jankrcal commented on collections/_infographics/energetika/elektrina-mix-eu.md
> +**Hlavním zdrojem elektřiny Česka je stále uhlí**, které má skončit v roce 2033[^programove-prohlaseni]. Dalším významným producentem elektřiny jsou **čtyři bloky v jaderné elektrárně Dukovany a dva
Výstavba za mě taky ok.

2023-02-27 14:59 UTC, katkolouchova commented
Díky za poznámky, všechny jsem zapracovala a taky díky za upozornění na přebytečné soubory, na ty jsem zapomněla. Co se týče dat za 2022, já už tu grafiku mám dokonce hotovou, akorát jsme posléze zjistili, že ta data jsou jen pro EU, tedy ani ne pro GB, což by ani tak nevadilo, ale nejsou pro další země světa, které pak taky chceme zařadit do seriálu na soc. sítě – z toho důvodu jsme zůstali u 2021, aby to bylo jednotné a všechna data byla ke stejnému roku. Dává ti to smysl?

2023-02-27 15:15 UTC, jankrcal approved these changes
super, s tímto vysvětlením je 2021 úplně ok

2023-02-27 15:39 UTC, merged