Přidání ceny Josefa Vavrouška
faktaoklimatu/web-cz pull request #1225
Opened 2023-07-10 11:52 UTC by jankrcal

Kromě toho přidává odkazy (odkaz na AFO neexistuje) a upravuje pořadí na
most-recent-first.

2023-07-11 07:06 UTC, jankrcal commented
@katkolouchova Můžeš prosím kouknout na tuto drobnost? Ondráš to viděl, tedy mě zajímá hlavně technické / designové oko...

2023-07-12 11:20 UTC, katkolouchova requested changes
Za mě ok, jen se mi tady moc nelíbí kombinace bold + underline. Tak bych to nechala bez podtržení a zvýrazní se to jenom po najetí myší. A klidně bych odstranila i tu ikonku indikující odkaz.

A v ideálním případě by mohlo být pěkné mít klikatelný celý box, jako je to u témat nahoře. Že by se po najetí trochu zvýraznila ta fialová bublina :)

2023-07-12 12:49 UTC, jankrcal commented
Hmm, hmm, souhlasím, že to je trochu hnusný.

Tvůj návrh se mi moc nezdá, protože bez underline (a bez ext-link icon) vůbec nepůjde poznat, že to je odkaz.
Nemáme pro to žádný precendent, odkazy bez underline jsou jen tlačítka nebo nějaké jasné UI prvky.

Dělat z toho tiles (zvýraznění bubliny) jsem v rychlosti zkoušel, ale je to trochu pracnější a nechce se mi na tom pálit moc času. Současně se mi to taky úplně nezdá, protože jedna z těch cen nemá link a přijde mi to špatný, když člověk vizuálně nepozná, co je link a co ne.

Tak nevím, jak z toho ven. 

- Můžu oddělat bold u odkazů a nechat ho jen u toho neodkazu.
<img width="1157" alt="Snímek obrazovky 2023-07-12 v 14 47 55" src="https://github.com/faktaoklimatu/web-cz/assets/145227/6449bcef-e08e-4453-8116-ceb98be8fcf6"> To mi přijde divný.

- Nebo odstranit bold úplně
<img width="1166" alt="Snímek obrazovky 2023-07-12 v 14 48 28" src="https://github.com/faktaoklimatu/web-cz/assets/145227/f15608a4-06ae-4ba7-8fc6-1572c9bb890a">
To mi přijde trochu nevýrazný, ale asi nejlepší z možností bez strong+underline.

Za sebe bych asi stejně zůstal u současného trochu hnusného...

2023-07-12 12:57 UTC, katkolouchova commented
Jojo, tak to nechme, jak to je, souhlas, že s těch zkoušených variant je toto stále nejlepší :) A třeba časem přijdeme na něco lepšího. Díky za otestování variant! :)

2023-07-12 12:57 UTC, katkolouchova approved these changes

2023-07-12 12:59 UTC, jankrcal commented
Díky!

2023-07-12 12:59 UTC, merged