Úprava údajů v grafikách
faktaoklimatu/web-cz pull request #1241
Opened 2023-08-03 12:52 UTC by marcel-otruba

2023-08-03 14:24 UTC, katkolouchova approved these changes

2023-08-04 08:02 UTC, mgrabovsky requested changes
V nových SVG jsou texty místo křivek.

2023-08-04 09:13 UTC, marcel-otruba commented
Díky za upozornenie, Chyba nastala pri opakovanom exporte SVG. Pushol som upravené verzie.

2023-08-04 09:38 UTC, mgrabovsky approved these changes

2023-08-04 12:33 UTC, merged