[WiP] Grafika světové dohody
faktaoklimatu/web-cz pull request #678
Opened 2020-10-25 09:44 UTC by protivinsky

WiP PR pro #434 
- [ ] finalizovat grafiku @kikinna - krom úprav od Lucky (o kterých předpokládám víš) je teď také grafika divně uříznutá - nadpis kousek čouhá přes ořez náhledu na stránkách, ze seznamu organizací vpravo je odříznutá horní organizace. 
- [ ] review textu @protivinsky 
- [ ] technické detaily @mukrop - zvažuji nějaký další tag, například "dohody" v topics tagech (případně by šlo i "úmluvy" nebo "mezinárodní spolupráce", jestli ti to zní lépe). Nicméně když přidám tag do md souboru s průvodním textem, nezobrazí se mi štítek nahoře na stránce s ostatními štítky. Musím ho přidat ještě někam jinam? Zároveň jsem trochu ztracený, jakou mám nastavit váhu - většinou použiju něco podobného předchozím grafikám, jen většina přirozených čísel je zabraná, tak začínám používat racionální čísla.

Zde náhled, ilustrující o čem píšu:
![image](https://user-images.githubusercontent.com/9573993/97103796-b1e6b080-16a6-11eb-8f02-31096fe46b58.png)

2020-10-26 13:00 UTC, mukrop commented
* Novy stitok musi byt zadefinovany aj v `_data/tags.yml` s popisom. Ale nerad by som zavadzal novy stitok, ak v nom bude len jedna vec. Ako minimum by som bral 2 objekty, preferovane aspon 3.
* Vaha: Racionalne cisla su OK, aj ked trochu atypicke :D. Vahy sa mozu aj opakovat, ale potom uplne nemas kontrolu nad poradim veci s rovnakou vahou (ale moze ti to byt jedno). Zasadne rozhodnutie je, ci chces tak vyznamnu vahu, aby sa to zobrazovalo v prvych 6 objektoch v sekcii na titulnej strane.

2020-10-26 14:48 UTC, ondraspribyla commented
Myslím, že přidávat štítek asi moc vhodné není. Spiš bych rozšířil sekci
OPATŘENÍ a přidal tam i tyhle dohody - jsou to svým způobem taky opatření -
jako další by tam třeba mohla být i Pařížská dohoda
Takže sekce by se mohla jmenovat "Opatření, dokumenty, dohody" ?
Co vy na to ?


On Sun, 25 Oct 2020 at 10:45, Tomas Protivinsky <notifications@github.com>
wrote:

> WiP PR pro #434 <https://github.com/faktaoklimatu/web/issues/434>
>
>    - finalizovat grafiku @kikinna <https://github.com/kikinna> - krom
>    úprav od Lucky (o kterých předpokládám víš) je teď také grafika divně
>    uříznutá - nadpis kousek čouhá přes ořez náhledu na stránkách, ze seznamu
>    organizací vpravo je odříznutá horní organizace.
>    - review textu @protivinsky <https://github.com/protivinsky>
>    - technické detaily @mukrop <https://github.com/mukrop> - zvažuji
>    nějaký další tag, například "dohody" v topics tagech (případně by šlo i
>    "úmluvy" nebo "mezinárodní spolupráce", jestli ti to zní lépe). Nicméně
>    když přidám tag do md souboru s průvodním textem, nezobrazí se mi štítek
>    nahoře na stránce s ostatními štítky. Musím ho přidat ještě někam jinam?
>    Zároveň jsem trochu ztracený, jakou mám nastavit váhu - většinou použiju
>    něco podobného předchozím grafikám, jen většina přirozených čísel je
>    zabraná, tak začínám používat racionální čísla.
>
> Zde náhled, ilustrující o čem píšu:
> [image: image]
> <https://user-images.githubusercontent.com/9573993/97103796-b1e6b080-16a6-11eb-8f02-31096fe46b58.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/faktaoklimatu/web/pull/678
> Commit Summary
>
>    - WiP svetove dohody
>
> File Changes
>
>    - *A* _infografiky/opatreni/svetove-dohody.md
>    <https://github.com/faktaoklimatu/web/pull/678/files#diff-f63e62bbae54a0c48fe1cadcf2086706dc35a9ff263c581f26e0f4d2296748b7>
>    (114)
>    - *A* _infografiky/opatreni/svetove-dohody.pdf
>    <https://github.com/faktaoklimatu/web/pull/678/files#diff-896c959c248af990e5784e7778ad8135e5bdf67ef326af3956d2da05817a0a48>
>    (0)
>
> Patch Links:
>
>    - https://github.com/faktaoklimatu/web/pull/678.patch
>    - https://github.com/faktaoklimatu/web/pull/678.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web/pull/678>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EH64XX23XMZKFHM5NTSMPXSRANCNFSM4S6GY3DA>
> .
>

2020-10-30 14:04 UTC, protivinsky commented
Tedy namísto sekce "Adaptační a mitigační opatření" bychom měli "Opatření, dokumenty, dohody"? Za mě to dává smysl, jsem pro. Štítek pak může zůstat prostě "opatření". Budeme pak s touto změnou muset i přepsat popis sekce.

2021-01-04 11:00 UTC, ondraspribyla commented
@katkolouchova v podstatě dokončila grafiku, vracím se tedy k tomuto PR. Myslím, že k dokončení je potřeba: 
1. Přepsat název a text sekce na Opatření, dokumenty, dohody
2. Finalizovat formátování textu (s tím, že nově bude k dispozici viditelný **obsah**)
3. Obsahové review textu (přišlo by mi fajn, aby to přečetl někdo, kdo standardně review nedělá - a abychom si takto "zacvičili" další lidi do review procesu) - @protivinsky @katkolouchova - oslovíte někoho? 

Chybí podle vás k dokončení ještě něco?

2021-01-16 21:16 UTC, protivinsky commented
@ondraspribyla zreviewoval jsem po Lucce a udělal ještě všelijaké textové změny. Výhledově možná budeme muset upravit, pokud se USA znovu připojí k Paříži.

Buď to pročti anebo dej vědět, že to už dělat nebudeš a já poprosím o technické review Martina.

2021-01-17 19:43 UTC, mgrabovsky commented
Provedl jsem ještě rychlou korekturu.

2021-01-18 12:14 UTC, ondraspribyla commented
Textově je stránka asi good enough. (nedokážu posoudit dobře, protože se mi grafika nezobrazuje v local buildu, takže jsem musel srovnávat text) 

@mgrabovsky  / @protivinsky Lze nějak snadno vyřešit to obrovské množství technických commitů a způsobit, že se bude zobrazovat grafika v současném stylu, tedy včetně obsahu? 

@protivinsky - v commentu z 30 Oct jsme se domlouvali, že zaředíme grafiku do sekce opatření, kterou přejmenujeme a přepíšeme úvodní text k sekci - to jsem ale nenašel. Dělal jsi tuto změnu?

2021-01-18 16:48 UTC, mgrabovsky commented
> Lze nějak snadno vyřešit to obrovské množství technických commitů a způsobit, že se bude zobrazovat grafika v současném stylu, tedy včetně obsahu?

Právě jsem udělal rebase na aktuální master, což nás zbavilo nesouvisejících commitů a měl by se zobrazovat i obsah.

2021-01-18 16:54 UTC, protivinsky commented
@mgrabovsky diky za opravu! Ja udelal local rebase, ale bez force-push. Takze se to minimalne u me zobrazovalo spravne s obsahem, ale historie commitu byla hrozny neporadek.

2021-01-18 16:56 UTC, mgrabovsky commented
@katkolouchova U Zeleného klimatického fondu je „k financování klimatick**á**ch opatření“.

2021-01-18 18:16 UTC, katkolouchova commented
> 
> 
> @katkolouchova U Zeleného klimatického fondu je „k financování klimatick**á**ch opatření“.

Opraveno.

2021-01-22 09:29 UTC, mukrop requested changes
Presiel som a optravil drobnosti, cestinu a pod. Este prosim:
* [x] Pridat infografiku (je tam len placeholder prazdny obdlznik, neviem, ci zamerne alebo omylom).
* [ ] Upravit text odkazov v zdrojoch, aby viac vysvetlovat, co za nimi je namiesto koho web to je. Napr. namiesto "MZP" napisat "Cesky preklad textu parizskej dohody [MZP]" alebo nepisat len "Ekolist" ale o com ten clanok je (kludne kopiu nazvu) a medium ked tak na koniec do zatvorky.

2021-01-23 20:37 UTC, ondraspribyla commented
Přepsal jsem texty (byly v nich věcné chyby a pokusil jsem se je udělat více relevantní)
Natextoval jsem odkazy (snad tak, že je jasné kam vedou)

Ready to Merge. @mukrop 
Je možné, že text potřebuje ještě malý proofreading (protože vím, že po sobě občas nechávám chyby)

2021-01-23 21:57 UTC, mukrop approved these changes

2021-01-23 22:01 UTC, merged