Redesign doprovodne texty
faktaoklimatu/web-cz pull request #722
Opened 2021-01-04 15:19 UTC by jankrcal

Tento PR aktualizuje design doprovodných textů, aby lépe fungoval pro delší texty.
 - Zvětšuje písmo a zkracuje řádky pro větší rozlišení.
 - Přidává automaticky generovaný TOC (pokud má stránka aspoň tři nadpisy). Pro velké rozlišení vyhřezává TOC nalevo mimo hlavní pruh stránky.
 - Definuje boxy v textu, které pro velké rozlišení vyhřezávají napravo mimo hlavní pruh stránky.
 - Definuje prolinkovávací boxy v textu (odkazy na jinou infografiku / jiné inforgrafiky).

TODO:
 - Někdy mi úplně dobře nefungovalo zvýrazňování aktuální sekce, potřeba víc otestovat.
 - Text stránky cykly-koncentrace-co2 je zatím experimentální, je potřeba před merge trochu doleštit.

2021-01-04 15:28 UTC, jankrcal commented
Matěji, Martine, můžete se prosím podívat na moje designové návrhy?

2021-01-05 15:47 UTC, mukrop requested changes
Fuha, to su dost velke zmeny, ale dobrym smerom :-). Par komentarov nizsie.

* Celkovo vaham, ci ten novy format nie je prilis uzky. U mna je to len stredna tretina monitora a nevyzera to ppodla mna moc dobre (pride mi to akoze som si kupil poriadny monitor na to, aby stranka prehlasila, ze na 60–70% sirkynebude obsah). Neslo by to aspon trochu sirsie?
* Vidim, ze longread ma vaccsie pismo (`1.1rem`). S celkovym zvacsenim pisma v textoch asi suhlasim, ale pride mi nesystemove nastavit 1.1 pre longread. Zvazoval by som radsej zvacsit `rem` pre celu stranku. Otazka potom znie, ci naozaj chceme mensie pismo pre sidebar a popis pod obrazkom, ci jednoducho nedame vsade o ten kusok vascie (neskusal som to, ale mohlo by to byt podla mna OK).
* Nemeni sa zobrazovanie objektov, ktore nema layout infografiky (teda veci s layoutom reserse/studie). Navrhoval by som to asi zmenit spolu.
* Vyclenenie `preview-block` z `preview-blocks` je fajn modularizacia, ale pride mi, ze `text-box` a `preview-box` by mohli byt jeden include, ktory len bude zobrazovat iny obcas podla toho, ci ma nastaveny aj infografiku alebo nie. Inak ten preview box je velmi pekny (ako koncept), obzvlast pre odkazovane infografiky!
* Vidim, ze text box sa zobrazuje na 50% sirky stranky na mobile. Vaham, ci to nie je prilis male, ci to radsej nestackovat nad seba (ale nie je to silny nazor). (Unrelated: Na mobilnej velkosti by sme asi mali zarovnavat text dolava a nie do bloku. Myslim, ze to aj bolo, ale asi to niekto niekedy omylom zrusil...)
* Bocny box mi graficky pride dost rusivy, ked je v tej svietivej modrej. To je farba, ktoru staticky temer vobec nepouzivame (myslim, ze skoro vyhradne ako hover na odkazy). Za mna prilis puta pozornost (a trochu rozhadzuje design, kedze sa inde prominentne nepouziva). Navrhol by som bud vsetko bezne/sede, alebo ciaru/nadpis bezne modry a text ovycajne cierny/sedy. Semanticky, bocny box ma za mna mensi vyznam (a teda ma putat mensiu pozornost) ako hlavny text.
* Tem graficky rozcestnik na vrchu porovnania transformacnych scenarov mi pride trochu nestastny. Je super, ze zobrazuje ukazky infografik (to je vyrazne lepsie ako aktualny stav), ale je hrozne velky, na mojom velkom monitore je vyskovo skoro cez celu obrazovku a ledva vidim zaciatok textu. Co takto to dat na bok ako preview-box? Bud vsetky 4 scenare pod seba, alebo odkazovat nejako inak (naopak pouzitie preview-box z jednotlivych scenarov na porovnanie mi pride super!). Celkovo mi totiz pride, ze zavadzame koncept/graficky prvok, ktory je pouzity len tu 1x a to mi pride neperspektivne.
* TOC je sympaticky. Aktualne mi sice pride trochu prilis vlavo, ale to by sa asi vyriesilo tym trochu sirsim strednym stlpcom. Ale vaham, ze je asi moc vyrazny, chcel by som, aby bol menej vyraznejsi ako text (text dolezitejsiu semantiku). Takze by som vyskusal napriklad dat ho cely sedym? Co myslite?
* Inak TOC niekedy funguje trochu nestastne. napriklad na `srovnani-energetickych-scenaru-cr` vidno, ze sa zvyraznuje vzdy najspodnejsi objekt, ktory je na stranke vdiet. Co ma v praxi nasledok, ze ked kliknem na nejaky nadpis, tak sa obrazovka posunie, ale zvyrazni sa iny nadpis ako ten, na ktory som klikol (to mi pride dost nestastne).
* Vidim, ze TOC sa generuje len pre dlhsie stranky. Ale napriklad `koncentrace-co2` mi pride dostatocne dlha na to, ze by sa mi tam zdal uzitocny. Nebolo by lepsie (v ramci konzistencie a least-surprise principu) ho jednoducho generovat vsade? Obzvlast ak bude sedy a trochu menej putat pozornost, tak podla mna ani na kratkej stranke nebude prilis zavadzat (aj ked uzitocny tam tiez nebude).
* Drobnost: Menil som navbar (je iny v dev a produkcii), takze som upravil aj TOC, aby sa zobrazoval sticky v takej vyske, ako zoddpoveda vyske navbaru (default `56px`, v pripade potreby to upravi JS po nacitani stranky).
* Prosim pri aktualizacii branchu nerobit merge, ale rebase na aktualny master. Vzhladom na politiku linearnej historie by sa pri finalnom merge aj tak robil rebase, takze vsetky konflitky sa musia vyriesit znova. Rebase som urobil, dufam, ze som vsetky konflitky vyriesil spravne (ak by bolo treba, u mna je este lokalna kopia povodnej vetvy).
* Pridal som commit s malymi zmenami (MD linter a zrusene nejake zbytocne zalamovanie riadkov).

Zaverom, pride mi to super praca vybornym smerom, len sa trochu bojim, ze zbytocne robime vela zmien naraz. Osobne by som radsej videl samostatne PR na sirku a velkost textu, ToC, preview-boxy. Kazdy koncept ma totiz samostatne ladenie a ked je to takto spolu, tak sa to trochu pletie a interferuje a clovek musi riesit vsetko naraz...

Aky je dalsi postup? Starete sa o toto @jankrcal alebo @mgrabovsky?

2021-01-06 08:52 UTC, mukrop commented
Na ilustraciu sirky a velkosti textu, ktory sa mi dobre cita: https://ec.europa.eu/easme/en/section/life/calls-proposals
(Ako to mate ostatni?)

2021-01-06 18:32 UTC, mgrabovsky commented
Dávám jenom na srozuměnou, že bych se na redesignu ještě rád podílel, ale nemám teď kapacitu se tomu věnovat. Kouknu na to a vyjádřím se během víkendu.

2021-01-06 19:04 UTC, jankrcal commented
Předně: děkuju moc za podrobné komentáře, připomínky a návrhy.

Ad velikost PR: rozumím a souhlasím. Tohle ale zrovna byl případ, kdy to chci vidět všechno najednou, abych si udělal názor na jednotlivosti. Zatím ještě upravuju v tomto velkém PR, ať to vidí o víkendu Matěj v celku. Na finální ladění to můžu rozdělit na menší PRs.

Na jednotlivé komentáře odpovím inline.

2021-01-06 19:43 UTC, jankrcal commented
> Fuha, to su dost velke zmeny, ale dobrym smerom :-). Par komentarov nizsie.
> 
> * Celkovo vaham, ci ten novy format nie je prilis uzky. U mna je to len stredna tretina monitora a nevyzera to ppodla mna moc dobre (pride mi to akoze som si kupil poriadny monitor na to, aby stranka prehlasila, ze na 60–70% sirkynebude obsah). Neslo by to aspon trochu sirsie?

Čekal jsem trochu kontroverzi :) Měřil jsem si délky řádků na různých webech a různé zpravodajské weby / medium / carbon brief se pohybují mezi 70 - 90 znaky na řádek. Můj současný návrh je v maximálním rozlišení okolo 75, což uznávám je docela radikální. To, cos poslal, má 110, což mi přijde na dlouhý texty moc (oni to podle mě trochu opticky zlepšují tím, že to je hodně velký font).

Upravil jsem css tak, že i ten hlavní sloupec textu s více místem trošičku roste, takže na mém externím monitoru se dostanu asi na 90 znaků na řádek. Jak Ti to přijde teď?

> * Vidim, ze longread ma vaccsie pismo (`1.1rem`). S celkovym zvacsenim pisma v textoch asi suhlasim, ale pride mi nesystemove nastavit 1.1 pre longread. Zvazoval by som radsej zvacsit `rem` pre celu stranku. Otazka potom znie, ci naozaj chceme mensie pismo pre sidebar a popis pod obrazkom, ci jednoducho nedame vsade o ten kusok vascie (neskusal som to, ale mohlo by to byt podla mna OK).

Větší písmo všude jsem zkoušel, nepřišlo mi to v sidebaru dobré. Zvětšit rem pro celou stránku a mít sidebar třeba 0.9 je možnost, asi čistší než současný stav. Neupravoval jsem, nechal bych na samostatný PR k velikosti písma.

> * Nemeni sa zobrazovanie objektov, ktore nema layout infografiky (teda veci s layoutom reserse/studie). Navrhoval by som to asi zmenit spolu.

Á, naprosto souhlasím, nechal jsem na detailní PRs.

> * Vyclenenie `preview-block` z `preview-blocks` je fajn modularizacia, ale pride mi, ze `text-box` a `preview-box` by mohli byt jeden include, ktory len bude zobrazovat iny obcas podla toho, ci ma nastaveny aj infografiku alebo nie. Inak ten preview box je velmi pekny (ako koncept), obzvlast pre odkazovane infografiky!

Souhlasím, hotovo.

> * Vidim, ze text box sa zobrazuje na 50% sirky stranky na mobile. Vaham, ci to nie je prilis male, ci to radsej nestackovat nad seba (ale nie je to silny nazor). (Unrelated: Na mobilnej velkosti by sme asi mali zarovnavat text dolava a nie do bloku. Myslim, ze to aj bolo, ale asi to niekto niekedy omylom zrusil...)

Nechtěné, opraveno.

> * Bocny box mi graficky pride dost rusivy, ked je v tej svietivej modrej. To je farba, ktoru staticky temer vobec nepouzivame (myslim, ze skoro vyhradne ako hover na odkazy). Za mna prilis puta pozornost (a trochu rozhadzuje design, kedze sa inde prominentne nepouziva). Navrhol by som bud vsetko bezne/sede, alebo ciaru/nadpis bezne modry a text ovycajne cierny/sedy. Semanticky, bocny box ma za mna mensi vyznam (a teda ma putat mensiu pozornost) ako hlavny text.

Zvolil jsem obyč text, světlý nadpis, souhlasím, je to rozhodně lepší.

> * Tem graficky rozcestnik na vrchu porovnania transformacnych scenarov mi pride trochu nestastny. Je super, ze zobrazuje ukazky infografik (to je vyrazne lepsie ako aktualny stav), ale je hrozne velky, na mojom velkom monitore je vyskovo skoro cez celu obrazovku a ledva vidim zaciatok textu. Co takto to dat na bok ako preview-box? Bud vsetky 4 scenare pod seba, alebo odkazovat nejako inak (naopak pouzitie preview-box z jednotlivych scenarov na porovnanie mi pride super!). Celkovo mi totiz pride, ze zavadzame koncept/graficky prvok, ktory je pouzity len tu 1x a to mi pride neperspektivne.

Jo, souhlasím, to byl takový experiment. Zkusil jsem dát všechny 4 pod sebe na bok, přijde mi to o dost lepší. Co myslíš?

> * TOC je sympaticky. Aktualne mi sice pride trochu prilis vlavo, ale to by sa asi vyriesilo tym trochu sirsim strednym stlpcom. Ale vaham, ze je asi moc vyrazny, chcel by som, aby bol menej vyraznejsi ako text (text dolezitejsiu semantiku). Takze by som vyskusal napriklad dat ho cely sedym? Co myslite?

Udělal jsem, posunul jsem ho o trochu víc ke středu.

> * Inak TOC niekedy funguje trochu nestastne. napriklad na `srovnani-energetickych-scenaru-cr` vidno, ze sa zvyraznuje vzdy najspodnejsi objekt, ktory je na stranke vdiet. Co ma v praxi nasledok, ze ked kliknem na nejaky nadpis, tak sa obrazovka posunie, ale zvyrazni sa iny nadpis ako ten, na ktory som klikol (to mi pride dost nestastne).

Taky se mi to zdá trochu rozbité, nechal bych na ladění na samostatný PR.

> * Vidim, ze TOC sa generuje len pre dlhsie stranky. Ale napriklad `koncentrace-co2` mi pride dostatocne dlha na to, ze by sa mi tam zdal uzitocny. Nebolo by lepsie (v ramci konzistencie a least-surprise principu) ho jednoducho generovat vsade? Obzvlast ak bude sedy a trochu menej putat pozornost, tak podla mna ani na kratkej stranke nebude prilis zavadzat (aj ked uzitocny tam tiez nebude).

Částečně souhlasím, změnil jsem hranici na >1 stránku. Tedy bych nechtěl mít TOC pro stránku jen s jednou sekcí, to vypadá hodně blbě. Se dvěma to vypadá taky trochu divně, ale už to má aspoň nějaký smysl.

Dal jsem to celé šedé, je to za mě o hodně lepší.

> * Drobnost: Menil som navbar (je iny v dev a produkcii), takze som upravil aj TOC, aby sa zobrazoval sticky v takej vyske, ako zoddpoveda vyske navbaru (default `56px`, v pripade potreby to upravi JS po nacitani stranky).

Díky.

> * Prosim pri aktualizacii branchu nerobit merge, ale rebase na aktualny master. Vzhladom na politiku linearnej historie by sa pri finalnom merge aj tak robil rebase, takze vsetky konflitky sa musia vyriesit znova. Rebase som urobil, dufam, ze som vsetky konflitky vyriesil spravne (ak by bolo treba, u mna je este lokalna kopia povodnej vetvy).

Jejda, pardon, moje chyba, díky za opravu. Já jsem to dělal tlačítkem na Githubu a přísahal bych, že na něm bylo "rebase", pak jsem byl překvapený, že ten commit pojmenoval "merge ...", ale už jsem to neměl čas řešit.

> * Pridal som commit s malymi zmenami (MD linter a zrusene nejake zbytocne zalamovanie riadkov).

Díky!

> Zaverom, pride mi to super praca vybornym smerom, len sa trochu bojim, ze zbytocne robime vela zmien naraz. Osobne by som radsej videl samostatne PR na sirku a velkost textu, ToC, preview-boxy. Kazdy koncept ma totiz samostatne ladenie a ked je to takto spolu, tak sa to trochu pletie a interferuje a clovek musi riesit vsetko naraz...
> 
> Aky je dalsi postup? Starete sa o toto @jankrcal alebo @mgrabovsky?

Počítám s tím, že to budu táhnout. Budu rád za pomoc od Matěje...

2021-01-06 21:36 UTC, mukrop commented
Uz nebudem reagovat inline, bolo by to prilis dlhe.

* Sirka textu: Takto uz mi to pride OK. Stale vaham, co si o tom myslim, ale takto uz asi dobre :-).
* Zvacsit rem a zmensit sidebar mi pride cistejsie, ale uvidime, co to urobi s bielym miestom. Viacero marginov a paddingov je totiz viazane na rem.
* Farebnost bocneho boxu: Lepsie, ale stale vaham, ci to moc netaha pozornost. Ten svetly modry nadpis myslim. Pride mi, ze ma to trochu rusi od flow textu niecim, co je len menej dolezite ako hlavny text. Preco mas vlastne pocit, ze to chces mat takto vyrazne oddelene aj farebne? S tmavomodrou ciarou a tmavomodrym nadpisom to nevyzeralo dobre?
* 4 scenare energetiky pod sebou za mna nie su 100% idealne, ale ovela lepsie ako ten stvorec a podla mna dostatocne dobre na to, ze viac by som to uz neriesil.
* TOC viac k stredu lepsi, sedy tiez lepsi, mozno by som ho ale predsa len dal trochu nizsie (takto skoro zashuje do modreho tiena hornej listy).
* Ad samostatne PR: To som myslel skor do buducna. Ked uz to je rozpracovane takto, viem si predstavit dokoncit to spolu. Nechavam na tebe.

Za mna super, paci sa mi, kam to ide :-). Este som zvedavy na Matejove postrehy cez vikend.

2021-01-07 06:32 UTC, jankrcal commented
Jen rychlý komentář bez programování:
 - Boční box bez zvýraznění jsem vlastně ani nezkoušel (vycházel jsem z Atlasu, kde to je barevně zvýrazněné), stojí to za zkoušku.
 - S energetickýma scénářema možná ještě zkusím jeden experiment, ale souhlasím, že takto je to už good enough.
 - TOC bych (moc) níž nedával, protože na nízkém monitoru a s dlouhým TOC (třeba scénář Ember je dobrý test) už se to nevejde na obrazovku. Možná by to chtělo ještě vymyslet nějaké max-height a skrolování toho TOC.
 - Ad samostatné PRs: ono s tím ještě asi bude dost finalizační práce, tak to je možná lepší i jen pro sense of progress, nehledě na to, že tohle se těžko recenzuje. Zvážím.

2021-01-10 19:16 UTC, jankrcal commented
Drobné změny:
 - ještě jsem udělal box ve srovnání scénářů trochu jinak (trochu širší plovoucí, moc se mi to tak líbí),
 - aplikoval jsem nový design na layout studie a datasety.

U studií jsem to zatím aplikoval minimalisticky, nejsem z toho úplně nadšený, ale je to dostatečně dobré. Pokud tam dělat další změny, tak za mě spolu s explainery (až budeme mít představu, jaký chceme udělat layout tam), aby to bylo sladěné.

Matěji, podařilo se Ti na to kouknout přes víkend? Máš nějaký připomínky?

Pokud bys našel čas i na kód, obzvlášť bych ocenil, kdyby se Ti podařilo kouknout na to nedokonalý zvýrazňování aktuální sekce (pokud to nebude snadný opravit, tak taky můžeme zatím zvýrazňování vypnout).

Matěji, Martine, dělali jste někdo změny v _layouts/dataset.html a _layouts/infographics.html mimo ten div hlavního contentu? (zdá se mi to jako nějaké rebase artefakty, tak bych to revertnul)

2021-01-10 19:31 UTC, mukrop commented
Robim teraz na prekjladoch webu, takze sa k tomu uplne nedostanem. V layoutoch som nijake zasadne zmeny nevidel, ale nevidim tam ani nic, co by som nazval rebase artefakty. Len upozornujem, ze niektore veci su tam domnelo duplicitne, pretoze sidebar s metadatami sa na mobile zobrazuje s inym formatovanim a trochu pozdruzovanym obsahom, takze texty su ine, mozno ta poplietlo to.

2021-01-10 19:38 UTC, mgrabovsky commented
Zrovna jsem se na to chtěl kouknout. Dnes jsem pracoval na repozitáři grafik, tak se k tomu dostávám až teď.

2021-01-10 21:43 UTC, mgrabovsky commented
Jenom v rychlosti pár připomínek/pozorování.

* Jako „optimální“ délka řádku se [tradičně doporučuje](https://practicaltypography.com/line-length.html) 45–90 nebo 75–100 znaků. Když se dívám na stránky, které se mi dobře čtou, je to zhruba 60–80. Osobně při čtení delších textů silně preferuji kratší řádky, přičemž poslední revize mi připadá OK.
* Osobně mi jako ideální velikost textu na mých zařízeních přijde 16–18px, v závislosti na písmu a řádkování snesu i 21px. Současný stav mi přijde fajn. Souhlasím s nastavením „základní velikosti“ tak, aby měl doprovodný text velikost `1rem`. Na mobilech bych dal klidně i menší velikost než na větších zařízeních.
* Boxík mi skrze výraznou modrou taky přijde poněkud rušivý a pozornost odvádějící. Současný boxík s 2×2 infografikami se mi vcelku líbí, jenom bych z obrázků infografik vyhodil šítky – zdá se mi to už zbytečně přehlcené. Trochu jsem si s tím konceptem boxíku hrál už při prototypování rozcestníku a myslím, že něco jako následující (možná i se světlejším textem nebo pozadím) by vypadalo trochu lépe, ale je to jen rychlý mockup:
![Screenshot_2021-01-10 Srovnání scénářů transformace elektroenergetiky ČR](https://user-images.githubusercontent.com/134321/104136080-50c0a600-5394-11eb-8ab3-e2a728283243.png)
  (Jinak Bootstrap má [nějaké základní styly](https://getbootstrap.com/docs/4.0/content/figures/) pro boxíky s obrázky apod., na které bychom mohli navázat. Přinejmenším mi ze sémantického hlediska přijde vhodné použít pro boxíky tag `<figure>`.)
* Zrušil bych podtrhování odkazů v TOC, jinak se mi v plné velikosti zdá OK. V menších velikostech je to trochu kostrbaté.
* S kódem a designovými drobnostmi rád vypomůžu.

(Napsal jsem delší komentář, ale spadl mi prohlížeč, zrovna když jsem chtěl nahrát obrázek, proto jsem spíše stručnější. Detaily případně můžeme řešit v navazujících PR.)

2021-01-11 07:14 UTC, jankrcal commented
Díky za komentáře, Matěji. S tím, co píšeš, souhlasím:
 - za mě tagy vyhodit ze všech těchto boxů, opravdu to zbytečně ruší.
 - tvůj mock boxíku mi přijde fajn, nemám silný názor. Jen mě napadá, že by se muselo řešit, aby to dobře fungovalo jak na tomto modrém pozadí, tak na bílém pozadí.

Obecně, rád bych toto PR dotáhl před víkendem, aby se na to dalo na víkendu navazovat. Teď mám velmi hektický týden v práci, tak bych osobně už začal volit zkratky a zjednodušení (jako třeba vypnout zvýrazňování v TOC), abychom to dotáhli s rozumným úsilím.

2021-01-11 13:53 UTC, jankrcal commented
Drobný update: s Martinem jsem se domluvil, že dotáhnu / dotáhneme tento PR k merge nejpozději do zítřka, protože to blokuje jeho práci na rozdělování repa na základ a jazykové verze.

Matěji, jsi prosím schopný pomoct dnes nebo zítra večer? (pokud ne, není problém, nějak to dotáhnu sám)

2021-01-11 14:01 UTC, mgrabovsky commented
Plánuju se tomu věnovat dnes po páté.

2021-01-11 14:13 UTC, mukrop commented
Len to chcem trochu zjemnit: Nie je to zasadny blocker, ale potreboval som si rozvrhnut svoju pracu a teda vediet, ci zaintegrovat moje zmeny postupne hned, alebo cakat na doriahnutie tohto.

Mimochodom, ak si niekto najdete trosku casu (oznaceny je tam @mgrabovsky), tak tam mam drobny iny PR, na ktory by mohol niekto mrknut, nez ho vezmeme (aby aj moja praca prechadzala cez review).

2021-01-11 16:18 UTC, mgrabovsky commented
@jankrcal Vzal bych si tedy teď na starost následující:
- [ ] Vyhodit tagy z boxíku.
- [ ] Nastylování boxíku dle mého návrhu.
- [ ] Drobná změna stylu TOC (zejm. zrušit podtrhávání).
- [ ] Zrušit zvýrazňování v TOC.

Může být? Je tu ještě něco s vysokou prioritou?

2021-01-11 19:08 UTC, jankrcal commented
Super, děkuju!

Později večer se k tomu dostanu, zkusím dotáhnout zbytek.

Jen mi přijde podezřelá ta oprava zvýrazňování v TOC, jak jsi přišel na konstantu headingsOffset: -780?
Nezávisí to na výšce Tvého monitoru?

2021-01-11 19:49 UTC, mgrabovsky commented
> Jen mi přijde podezřelá ta oprava zvýrazňování v TOC, jak jsi přišel na konstantu headingsOffset: -780?
> Nezávisí to na výšce Tvého monitoru?

Na výšce monitoru záleží, ale myslím, že pro praktické ne moc. Zkoušel jsem i menší velikosti a zdálo se mi to dostačující. (Na mobilech už je to jiná věc, ale to pro nás teď není relevantní. Na 4K apod. jsem nezkoušel, je možné, že to taky nebude ideální.)

To číslo jsem vypočítal velmi hrubě jako rozdíl mezi výškou, kdy zvýraznění naskočí, a výškou, kdy bych jej čekal. V mém prohlížeči to vychází tak, že se sekce v TOC zvýrazní, když je nadpis od horního okraje vzdálený okolo 380px nebo méně.

Robustnější by bylo nastavit to dynamicky podle výšky prohlížeče, třeba na horní třetinu, ale to už mi teď přijde trochu zbytečné.

2021-01-11 22:14 UTC, jankrcal commented
> Robim teraz na prekjladoch webu, takze sa k tomu uplne nedostanem. V layoutoch som nijake zasadne zmeny nevidel, ale nevidim tam ani nic, co by som nazval rebase artefakty. Len upozornujem, ze niektore veci su tam domnelo duplicitne, pretoze sidebar s metadatami sa na mobile zobrazuje s inym formatovanim a trochu pozdruzovanym obsahom, takze texty su ine, mozno ta poplietlo to.

Co jsem měl na mysli je většina změn v infographic.html v tomto commitu:
https://github.com/faktaoklimatu/web-cz/pull/722/commits/ee0538254c692b697e4d8666162b27afdb7b2f64
(například změna div.download-buttons na aside.downloads-box).

Ten commit je údajně můj, ale vůbec si nepamatuju, že bych to měnil. Mám tak blbou paměť, nebo jsi tam Martine něco vpašoval?

2021-01-12 00:33 UTC, jankrcal commented
@mukrop a @mgrabovsky Prosím o další recenzi. Mělo by to být hotovo.

Matěji, po dělší době koukání z orámovaného boxíku nejsem úplně nadšený, je tam hodně čar. Ale pro teď každopádně good enough (leda, že by Martin měl silný názor).

Ten design mi ale hodně neseděl na čistě textový box, přišlo mi to hodně těžkopádný (trochu mi chybí slova na popisování designu :)). Tak jsem si přidal styl pro takové boxy.

@ondraspribyla Prosím o recenzi úprav stránky cykly-koncentrace-co2
(Nebyla to nejvhodnější stránka na překlopení textu z atlasu. Může tedy být, že moje spojení současného textu a atlasu nepřináší hodnotu, v tom případě to klidně můžu vrátit zpátky)

2021-01-12 07:38 UTC, mukrop commented
> Co jsem měl na mysli je většina změn v infographic.html v tomto commitu:
> [ee05382](https://github.com/faktaoklimatu/web-cz/commit/ee0538254c692b697e4d8666162b27afdb7b2f64)
> (například změna div.download-buttons na aside.downloads-box).
> 
> Ten commit je údajně můj, ale vůbec si nepamatuju, že bych to měnil. Mám tak blbou paměť, nebo jsi tam Martine něco vpašoval?

Mna prave vzdy prekvapi, ake semanticke HTML tagy vy vytiahnete a ja som netusil, ze existuju :-). `aside` som este nevidel, takze sa obavam, ze ten commit a zmena su naozaj tvoje.

2021-01-12 08:36 UTC, mgrabovsky commented on assets/js/main.js
> +            const targetEl = $(location.hash);
Tady by mělo stačit obalit `location.hash` jako `decodeURIComponent(location.hash)`.

2021-01-12 15:16 UTC, ondraspribyla commented
@jankrcal text cykly Co2 mi přijde dobrej, ale nechtěl jsem ztratit některé poznámky a odkazy, které z původního textu vedou. Doplnil jsem tedy ještě jednu sekci nakonec a tam je dal do odrážkového seznamu. (viz poslední commit) Je to tak ok?

2021-01-12 16:07 UTC, jankrcal commented
Děkuju, Ondráši. Souhlasím, jen jsem smazal předchozí kratší zmínku o acidifikaci oceánů, protože tam stejně moc nezapadala do příběhu.

2021-01-12 16:39 UTC, mgrabovsky commented on assets/js/main.js
> +            const targetEl = $(location.hash);
Opravil jsem.

2021-01-12 16:41 UTC, mgrabovsky commented
To globální nastavení velikosti písma na 110% je úmyslné, nebo to je zapomenutý experiment? Zdá se mi teď všechno hrozně velké a reflexivně zoomuju na 90%.

2021-01-12 16:51 UTC, mgrabovsky commented
> Mna prave vzdy prekvapi, ake semanticke HTML tagy vy vytiahnete a ja som netusil, ze existuju :-). `aside` som este nevidel, takze sa obavam, ze ten commit a zmena su naozaj tvoje.

Myslím, že to jsou moje úpravy. Asi se tam dostaly přes nějaký rebase :shrug:

2021-01-12 19:53 UTC, mgrabovsky approved these changes
Za mě jinak technicky OK.

2021-01-12 19:56 UTC, mukrop commented
Pockajte prosim este na mna, dostanem sa k tomu asi zajtra (max vo stvrok doobeda).

2021-01-12 21:23 UTC, jankrcal commented
Jasně, počkám, Martine!

Matěji, díky za review! A díky za opravu toho javascriptu, už to bylo pozdě večer a já byl dost unavenej, tak jsem trochu prasil :)

html {font-size: 110%} zvětšuje rem pro celou stránku, jak jsme se s Martinem shodli ze začátku diskuse. Tak aby long-read text měl velikost 1rem. Leckteré elementy jsem opět úměrně nebo téměř úměrně zmenšil, ale samozřejmě ne vše. Pokud je to kontroverzní, tak samozřejmě můžeme commit 77af512 revertovat nebo nějak předělat.

2021-01-13 15:18 UTC, mgrabovsky commented
Už chápu. Problém je v tom, že by se neměly používat relativní velikosti tam, kde referenční velikost není odkud dědit. (Což platí nepochybně pro kořenový prvek `<html>`.) V takovém případě se jako referenční velikost použije výchozí velikost textu nastavená v prohlížeči, což je myslím 16px (aspoň pro Firefox a Chrome, ale neověřoval jsem to), kdežto já mám nastaveno 18px. V důsledku jsem tedy text viděl jinak než vy.

Řešením je nastavit pro `html` absolutní velikost, třeba 17.6px (110%) nebo 18px (112,5%).

2021-01-13 15:50 UTC, jankrcal commented
Matěji, jsem přesvědčen, že to je v pořádku. Důvod, proč tam mám 110% a ne 17.6px je právě ten, abychom respektovali nestandardní nastavení prohlížeče / uživatele, viz např. https://www.vzhurudolu.cz/prirucka/jednotky.

Prostě velikost písma html nastavuju na 110% výchozí velikosti písma.

Jak se stalo, že máš výchozí velikost 18px? Nemá stejně tak spousta jiných webů velké písmo?

2021-01-13 16:42 UTC, mgrabovsky commented
> Matěji, jsem přesvědčen, že to je v pořádku. Důvod, proč tam mám 110% a ne 17.6px je právě ten, abychom respektovali nestandardní nastavení prohlížeče / uživatele, viz např. https://www.vzhurudolu.cz/prirucka/jednotky.

V tom případě, pokud chceme respektovat nastavení prohlížeče, nic jiného než 100% nebo 1em nedává smysl.

> Jak se stalo, že máš výchozí velikost 18px?

Patrně mi to takhle víc vyhovuje. V porovnání s jinými weby mi teď kažodpádně náš text přijde moc velký.

> Nemá stejně tak spousta jiných webů velké písmo?

Weby jsou různé – některé mají písmo velké, jiné malé, některé _just right._ Některé weby nastavují absolutní velikost pro velikost textu (třeba GitHub), jiné nastavují velikost textu relativní, ale velikosti prvků absolutní (třeba GMail), jiné zase nechávají velikosti všeho relativní (třeba zrovna vzhurudolu.cz – ten je na mé obrazovce obří a musím zoomovat na 70%, aby se mi četl příjemně).

[Nedá se říct,](https://css-tricks.com/is-it-better-to-use-ems-rems-than-px-for-font-size/) že by nějaký přístup byl vyloženě špatně. Samozřejmě záleží na nás, jak si to nastavíme.

Musím se přiznat, že jsem v našich stylech původně předpokládal jiný přístup, tudíž bych teď byl spíš pro, abychom nechali kořen na 100% a velikost písma, případně jiné velikosti násobili až níže v hierarchii. Dáva mi to takhle větší smysl i vzhledem k měřítkům různých prvků, boxíků, tlačítek, marginů apod., které momentálně vztahujeme ve větší míře ke kořeni (`rem`) než k sobě/rodičům (`em`).

2021-01-13 22:03 UTC, jankrcal commented
Matěji, Tvůj fix 5dddbda v principu revertuje můj předchozí fix a968278 (který zas možná revertoval nějaký tvůj ještě starší commit?). Můžeš prosím víc vysvětlit, proč to tak chceš?

Já chci a.is-active-link { bold}, protože mi přijde divné, když se když je active nějaká kapitola, tak se zvýrazňují tučně i všechny podkapitoly.

2021-01-13 22:16 UTC, jankrcal commented
Přijde mi, že je na autorech webdesignu, aby si vybrali, jestli má web spíš malé písmo nebo velké písmo. Stejně tak je na uživatelích, aby si mohli snadno celý internet zvětšovat nebo zmenšovat (pokud třeba špatně vidí nebo mají specifický monitor nebo specifické preference). Z toho pohledu mi přijde korektní pro skloubení obou přístupů nastavit html { font-size: 110% }

Ale předně nechci vést dlouhou filozofickou debatu o nastavování velikosti písma :) Přijde mi důležitý, aby se nám velikost písma na webu líbila.

Přijdou mi tu dvě ortogonální otázky:
1. relativní nebo absolutní hodnota pro font-size v html
2. zvětšit rem nebo nechat rem defaultní a nastavovat jednotlivé elementy.

Ad 1: Preferuju relativní, ale vlastně je mi to docela šumák.
Ad 2: Mně pořád přijde atraktivní původní teze upravit rem tak, aby hlavní body text měl velikost 1rem. Pokud by nás to nutilo k ručnímu zmenšování příliš mnoha věcí (např. z bootstrapu), tak už bych to ale nepodporaval.

Za sebe bych počkal bych na Martina a jeho pohled na věc.

2021-01-14 09:52 UTC, mukrop requested changes
Dobra praca, uz je to fakt skoro hotovo :-). Par poslednych postrehov nizsie.
* [x] Zvyraznovat vsetky nadpisy sekcie v TOC aj mne prislo divne, ale vidim, ze to Matej prave upravil.
* TOC mi pride, ze funguje dobre.
* [x] Zvazujem nadpis obsahu dat ako `h3` miesto `h2`. Aktualne mi totiz pride. ze sa vizualne bije s nadpismi v texte (stredne silna preferencia).
* Ked je sprievodny text super-kratky (napriklad http://localhost:4000/datasety/tropicke-dny), tak to vyzera dost divne, kedze tam nie je obsah a nie je jasne, preco je to zrazu uzsie. Ale asi mi to nevadi a suhlasim nechat to ako "good enough".
* [ ] Rozbili ste stranku s datasetom `emise-eu`, zle zobrazuje stlpce a neinterpretuje MD. ked sme pri tom, asi by som tie dva datove boxy dal pod seba.
* Stranky studii za mna good enough.
* [ ] Boxovanie suvisiacich infografik vedla sprievodneho textu sa mi uplne nepaci, Jenova verzia s ciarou bola podla mna o dost lepsia. Navyse aktualny stav je nekonzistentny (boxy na inforgrafiky, ale ciara na texty, vid http://localhost:4000/infografiky/cykly-koncentrace-co2). Mam silnu preferenciu mat to konzistentne, stredne silnu na ciaru oproti boxu.
* [ ] Aktualne stylovany perex (napriklad http://localhost:4000/infografiky/cykly-koncentrace-co2) sa mi nezda dobry. Je to prilis tazke, ked je cely odstavec boldom (perex byva aj v casopisoch vacsi, skoro nikdy nie tucny). Navyse vaham, aky to ma semanticky ucel, kedze nad tym je caption, ktory podla mna plni to iste. Mam silnu preferenciu nemat ho boldom, len slabu nemat ho tam oproti caption pod obrazkom (resp. mozno je este lepsia moznost mat tam perex vacsim pismom a vkladat tam text z caption, ktory vyhodime zpod obrazka).
* [ ] V komentari noveho JS je typo (table _of_ contents).

2021-01-14 09:53 UTC, mgrabovsky commented
> Matěji, Tvůj fix [5dddbda](https://github.com/faktaoklimatu/web-cz/commit/5dddbdac5f04357cd1517c0736847e45bc6f6cf5) v principu revertuje můj předchozí fix [a968278](https://github.com/faktaoklimatu/web-cz/commit/a968278a0fd1e33608a55ddcc0f090cb3a9100f6) (který zas možná revertoval nějaký tvůj ještě starší commit?). Můžeš prosím víc vysvětlit, proč to tak chceš?

Jejda, to jsem si nevšiml. Omlouvám se. Mě zase iritovalo, že se spolu s textem nadpisu nezvýrazňuje i číslo/odrážka, čehož jsem sice do jisté míry docílil, ale s nechtěným vedlejším efektem. Situaci už jsem napravil snad ku prospěchu všech.

> Přijdou mi tu dvě ortogonální otázky: […]

Co se týče dvou otázek, jsem jednoznačně pro relativní nastavení u `html` a tíhnu k `font-size` 100%/1rem.

Mám pocit, že se zvětšeným písmem v kořeni jsou obří nebo příliš výrazné některé prvky, u kterých to není nutné – menu, tlačítka, štítky atd. – a které bychom tedy museli zmenšovat. Proto mi přijde přirozenější nechat 100% a zvětšovat jenom tak, kde je to potřeba.

2021-01-14 10:00 UTC, mukrop commented
Aha, a este k ozehavemu pripadu velkosti pisma :-).
Asi nemam az taky silne vyhraneny nazor. Pride mi nevhodne nastavovat pre `html` absolutne cislo prave preto, ze tym ignorujeme ludi, ktori si sami upravuju velkost pisma v systeme, Posledny Matejov argument, ze vacsie rem zvacsuje aj veci ako tlacitka a potobne mi pride relevantny, takze asi suhlasim s tym, ze to moze zostat, ako je (tj. rem 100% a upravovane jednotlive elementy podla potreby). Prepac, Jeno, ze som ta prehnal upravovat to v kode na dvakrat (povodna pripomienka, ze by bolo mozno vhodne, aby vascina textu bola 1 rem bola moja).

2021-01-14 11:48 UTC, mgrabovsky commented
Měl jsem teď chvilku čas, tak jsem provedl některé změny:

* Nadpis obsahu jsem zmenšil, ale nechal jsem `h2`, protože sémanticky to líp odpovídá a navíc se mi tu víc líbí verzálky. (Ještě víc by se mi tak hodil řez semibold, ale ten nemáme k dispozici.) Zdá se ti to takhle lepší?
  ![Screenshot_2021-01-14 Srovnání scénářů transformace elektroenergetiky ČR](https://user-images.githubusercontent.com/134321/104582657-741f7580-5660-11eb-9b41-9ac566e73081.png)
* `emise-eu` jsem opravil. Byly tam zapomenuté HTML tagy.
* Boxíky jsem upravil na jednotný (Jeňův) styl.
* Typo v JS jsem opravil.

Ještě technická poznámka/prosba do budoucna: Styly by se měly psát stylem _mobile-first,_ tj. výchozí styl (bez media queries) udává, jak web bude vypadat na nejmenších zařízeních (na mobilech). První zarážka (media query s nějakou `min-width`) může být třeba pro větší mobily nebo tablety, druhá pro větší tablety, třetí pro běžné monitory atd.

Většina CSS frameworků (včetně Boostrapu) je na tenhle režim nastavená a počítá, že vývojáři jej budou taky následovat. My teď na různých místech mícháme _mobile-first_ a _desktop-first_ a někdy je to hodně matoucí. Nechce se mi to teď už přepisovat, ale rád bych, abychom na to při příštích úpravách mysleli.

2021-01-14 11:55 UTC, mukrop commented
Super, so zmenami sihlasim, dik.
Este by som poprosil nejaky nazor na ten perex, nech uzavrieme ten a urobim merge. (Moznost je aj, ze perex budeme riesit samostatne potom, pretoze je to vlastne separatna vec.)

2021-01-14 12:34 UTC, mgrabovsky commented
U perexu souhlasím, že tučnost trochu ruší. Pro mě plní funkci perexu popisek pod obrázkem, takže další perex v textu mi přijde redundantní a trošku matoucí. (Co vidím: Shora vidím navbar s logem, název infografiky, podnadpis v obrázku, grafiku samotnou ve zbytku obrázku, perex/popisek pod obrázkem, další perex v úvodu textu, první nadpis atd. Přijde mi toho trochu příliš najednou.)

Osobně bych zachoval text přímo pod obrázkem jako jediný perex a nějaké shrnutí s důležitými informacemi nechal tam.

2021-01-14 19:56 UTC, jankrcal commented
Perex jsem odtučnil, přijde mi to tak už lepší.

Mně caption grafiky nefunguje tak moc jako perex protože to má jinou šířku, je to horizontálně odsunutý a hlavně je to caption grafiky. Proto se mi líbí mít perex.

Současně to beru jako experiment, je to jediná grafika, která má perex. Pokud to budeme používat, tak je to stejně potřeba přesunout do metadat a mít to v html šabloně.

Jsem ochoten to jako koncept zrušit, ale nechal bych to spíš na další PR. Za mě to závisí na tom, jak budeme pracovat s perexama v explainerech, které třeba nebudou mít žádnou grafiku.

2021-01-14 19:57 UTC, jankrcal commented
Ad velikost písma: chápu to správně, že je poptávka po tom revertovat commit 77af512, který měnil rem?

Teď už ten revert asi nepůjde automaticky, zkusím to udělat.

2021-01-14 19:59 UTC, jankrcal commented
> Měl jsem teď chvilku čas, tak jsem provedl některé změny:

Díky za úpravy, přijde mi to vše super. (A dík za ochotu opustit svoji designovou vizi boxíků!)

> Ještě technická poznámka/prosba do budoucna: Styly by se měly psát stylem _mobile-first,_ tj. výchozí styl (bez media queries) udává, jak web bude vypadat na nejmenších zařízeních (na mobilech). První zarážka (media query s nějakou `min-width`) může být třeba pro větší mobily nebo tablety, druhá pro větší tablety, třetí pro běžné monitory atd.
> 
> Většina CSS frameworků (včetně Boostrapu) je na tenhle režim nastavená a počítá, že vývojáři jej budou taky následovat. My teď na různých místech mícháme _mobile-first_ a _desktop-first_ a někdy je to hodně matoucí. Nechce se mi to teď už přepisovat, ale rád bych, abychom na to při příštích úpravách mysleli.

Rád si to nechám někdy vysvětlit. Jde v principu o linting, o čitelnost kódu nebo to má nějaký podstatný dopad na funkčnost?

2021-01-14 21:34 UTC, jankrcal commented
Ještě jsem lecos doleštil na stylech boxů, jsem z toho teď už fakt nadšený, za mě můžeme zítra dopoledne nasadit (pokud ostatní souhlasíte).

2021-01-14 21:34 UTC, jankrcal commented
> Rád si to nechám někdy vysvětlit. Jde v principu o linting, o čitelnost kódu nebo to má nějaký podstatný dopad na funkčnost?

Už jsem ty výhody myslím pochopil, když jsem ty styly předělával. Mnohem přehlednější.

2021-01-15 09:43 UTC, mukrop approved these changes
Super, prehlasujem za hotove :-).

Este teda vidim, ze CSS obsahu je v `infographic.scss`, co mi pride uz trochu nevhodne (kedze to pouzivaju aj studie a datasety). Ale uz by som to neriesil. Mohol by si pripadne @mgrabovsky vyrobit issue so zoznamov veci na upratanie v CSS?

2021-01-15 09:44 UTC, merged