Oddělen kód od obsahu
faktaoklimatu/web-cz pull request #757
Opened 2021-01-28 15:54 UTC by mukrop

Tento PR vyclenuje funckionalitu webu do samostanteho repozitara `web-core`. Vyclenovanie este nie je uplne finalizovane (vo web-core je este dost ceskych textov v infrastrukture, ktore budu chciet prehodit do suboru s prekladom), ale jadro prace je urobene a otestovane na CZ/SK weboch.

Zakladna myslienka: V repe web-cz je obsah cleneny podla kolekcii a lokalne assety a lokalne includes. Podadresar web-core je repo s obsahom, ktore symlinkuje kolekcie do nadradeneho repozitara s obsahom. Prikazy pre `make` sa prepisuju a spustaju vo vnutronom repe `web-core`. Repozitar s obsahom je vzdy naviazany na konkretny commit `web-core`, ten je tak mozne vyvijat samostatne bez rizika rozbitia rapozitarov s obsahom. Zaroven rozdielne jazykove verzie mozu pouzivat rozny commit web-core (a teda updatovat postupne).

Tecnicke zmeny build procesu:
* Ruby gemy sa uz generuju lokalne, `Gemfile.lock` subor je priamo v repozitari, aby mali vsetci jednotny build. Aktualizacia commitu `web-core` a pripadna instalacia/aktualizacia novych Gemov sa robi automaticky pri lubovolnom volani `make` v repozitari s obsahom. Tj. na rozchodenie by malo stacit `clone` repa s obsahom a `make local`, submodul a gemy sa vyriesia automaticky (stale je potrebne mat nainstalovany jekyll, bundler a inkscape).
* Predosly bod ma nasledujuci dosledok: `make local` v repozitari s obsahom meni (moze menit) stav `web-core`, ale rovnake volanie v ramci `web-core` tiez funguje, avsak nemeni stav vnutorneho repa. Ak teda vyvijate nieco, co je v obidvoch repach (nova funkcionalita s novym jazykovym obsahom), je treba byt opatrny kde clovek vola build.
* Pri prechode z aktualneho buildu zostava v suborovom systeme vela artefaktov (generovane assety a stranka a cache v repozitari s obsahom). Pre vacsinu timu budem asi preto odporucat vytvorit si novy clone.

Na merge a zaskolenie ostatnych by bolo este treba aktualizovat Readme, ale zatial som na to nenasiel cas :-/. Ak sa k tomu dostanete na zaklade vasho testovania, pomoze to.

Tym, ze niekolko krat nastal rebase na aktualny master (kde sa toho v medzicase zmenilo celkom dost) bude treba preklikat co najviac stranok, klikat na odkazy a podobne a uistit sa, ze vsetko funguje ako ma. Pozreli by ste sa na to @mgrabovsky, @jankrcal prosim? Rad by som to dostal do mastra rozumne skoro, nech nemusim znova robit rebase na novy master (ono sa to nezda, ale je to tricky, lebo to treba robit v obidvoch repozitaroch a vyseparovat novy obsah od novej funkcionality).

2021-01-29 09:03 UTC, jankrcal commented
Dostanu se k tomu snad později dneska, teď potřebuju ještě chvíli pracovat.

Jinak bych prostě blokoval všechny další PR dokud se tohle nenasadí, věřím, že přes víkend / do pondělí to musíme zvládnout dotáhnout.

2021-01-29 09:11 UTC, mukrop commented
To by bolo super, dik.

2021-01-29 10:10 UTC, mgrabovsky commented
Já na to mknku asi taky až večer.

2021-01-29 13:16 UTC, mgrabovsky requested changes
Obecně to vypadá dobře. `make container` funguje, takže za mě spokojenost :) Našel jsem jenom pár drobností:

- [ ] Na stránce štítku je oproti oproti původnímu stavu trochu rozhozený popisek „Přehled oblastí a témat…“.

  ![Screenshot_2021-01-29 energetika](https://user-images.githubusercontent.com/134321/106279079-28fa8a80-623c-11eb-9635-a03ad79f836a.png)
- [x] Některé sekce nemají lokalizované názvy (infographics, datasets).
- Místo `local-{assets,includes}` by se mi o trochu víc líbilo `{assets,includes}-local` (mj. kvůli Tab-completion), ale nemám silný názor.
- Smazal jsem zapomenutou složku s layouty.

2021-01-29 13:16 UTC, mgrabovsky commented on .travis.yml
> +import: faktaoklimatu/web-core:.travis.global.yml@master
Chápu správně, že Travis bude tahat konfiguraci z masteru web-core bez ohledu na verzi submodulu?

2021-01-29 22:03 UTC, jankrcal approved these changes
Dobrá práce, nic dalšího zásadního tam nevidím, vše mi na lokálu fungovalo (kromě drobného bugu, co reportoval Matěj). Navíc mi funguje 'make local', takže já jsem spokojený. Přidávám drobné komentáře, ale za mě souhlas.

Trochu blbě se to recenzuje, protože nezkontroluju, že ty soubory na web-core jsou stejný. Tak bych to prostě nasadil a časem případný drobný problémy uvidíme.

2021-01-30 10:15 UTC, mukrop commented on Makefile
> +	cd $(WEB_CORE_FOLDER) && make $@
Ano, dik.

2021-01-30 10:16 UTC, mukrop commented on .travis.yml
> +import: faktaoklimatu/web-core:.travis.global.yml@master
Ano, je to tak. Idealnejsie by bolo z daneho submodule commitu, ale to neviem, ci vobec nejako pojde nastavit bez velkej masinerie. Travis config sa az tak casto nemeni, tak sa vtedy syncnu vsetky jazykove verzie.

2021-01-30 10:17 UTC, mukrop commented on _config.yml
> -        permalink: /:collection/:title
Bol len zabudnuty bordel (ktory sa mohol aj dodatocne vratit pri neopatrnom rebase).

2021-01-30 10:19 UTC, mukrop commented on _data/news.yml
> -  summary: "Podkladová data a grafika [Vývoj světové teplotní anomálie](/infografiky/vyvoj-teplotni-anomalie) byla převedena na _předindustriální_ referenční období, tedy 1850–1900. Důvodem je, že Pa
Tam vznikol konflikt. Zmena textu bola v povodnych commitoch a konflikt vznikol tym, ze sa menil slug z `/vyvoj-teplotni-anomalie` na `/teplotni-anomalie` a spravoval som to tu (je pravda, ze mozno som to mohol opravovat samostatne),

2021-01-30 12:21 UTC, mukrop reviewed
Vsetko opravene. Lokalizovanie nazvov kolekcii sa ukazalo ako trochu komplexnejsie, ale myslim, ze aktualne riesenie je primerane vseobecne. @mgrabovsky mrkni znova a daj ack,

(Stale teda chyba prerobit readme, ale to asi cez vikend nedam a nechcem z toho robit blocker.)

2021-01-30 13:13 UTC, mgrabovsky approved these changes

2021-01-30 13:44 UTC, merged