Nejvetsi emitenti
faktaoklimatu/web-cz pull request #759
Opened 2021-01-29 21:43 UTC by ondraspribyla

Textově asi jednoduchá grafika... nenapadlo mě nic dalšího co k tomu napsat. Kdyby vás něco napadlo, rád si doplním.

- [ ]  v datasetu je potřeba doplnit do výstupů tabulku největších emitentů (tam ale nemám práva sahat) - prosím @jankrcal o doplnění

2021-01-29 21:56 UTC, ondraspribyla commented
řeší issue #581

2021-01-29 22:17 UTC, crysman commented
I'm on it... :gear:

2021-01-29 22:29 UTC, crysman requested changes
hukot. good job!

zkontrolováno:
1. pravopis, gramatika, typografie: až na drobnosti OK, opravím
2. napočítal jsem jen 29 puntíků v mapě, mohl jsem se splést, nicméně, zkusil jsem to 3x, a 3x 29, nikoliv 31 jako uvádí text
3. nelíbí se mi některé formulace ("Zobrazené zdroje"), udělám v zápětí kosmetický commit s opravou

nezkontrolováno:
1. dataset (a tedy ty hodnoty a čísla)

2021-01-29 22:53 UTC, crysman commented
@ondraspribyla není pro mě zcela srozumitelné toto:
`Potvrzené emise Prunéřova se tímto snížily o 50 %.` - chápu to správně tak, že pokud bychom měli data z konce roku 2020, tak by tam Prunéřov měl polovinu kostiček?

2021-01-29 23:13 UTC, crysman commented
za mě hotovo, nicméně:

TODO:
1. objasnit záhadu s 31 versus napočítaných 29
2. aprrovnout moje review, zda OK
3. kontrola datasetu (a čísel)
2. zvážit ještě nějakou reformulaci toho s tím odstavcem s Prunéřovem - buď jsem natvrdlý, nebo se u toho možná trochu zaseknou i ostatní... za mě by pomohl explicitnější jazyk typu právě "_Prunéřov měl polovinu kostiček_"

2021-01-30 08:14 UTC, jankrcal commented
Kouknu na to. Někdy během víkendu. Mám dva body: 
 - Eliška dataset upravovala, tak ho od ní získám a případně dočistím.
 - Potřebujeme ještě podle mě trochu okomentovat slučování podniků pro účely zobrazení, navrhnu nějaký odstavec v rámci review.

2021-01-30 17:14 UTC, jankrcal commented
Ke crysmanovým komentářům:
 - objektů je 30, upravil jsem v textu (v grafice zobrazujeme v jednom bodě 2, má víc barev)
 - crysmanovy úpravy ok, dvě z nich jsem drobně změnil,
 - dataset jsem doplnil,
 - Prunéřov jsem reformuloval.

Kromě toho jsem přidal odstavec o slučování podniků. Prosím Ondráše o finální pohled na mé změny a merge.

2021-01-30 17:14 UTC, jankrcal approved these changes

2021-01-30 17:14 UTC, jankrcal commented
A prosím crysmana, aby odkliknul, že požadované změny jsou udělané.

2021-01-30 17:35 UTC, crysman commented on _infographics/emise/nejvetsi-emitenti-cr.md
> +* Protože jsou údaje z roku 2018, některé podniky již omezily či ukončily provoz v důsledku růstu cen emisních povolenek nebo prošly rozsáhlejší ekologizací.  Například v polovině roku 2020 byl ukonč
like this :+1:

2021-01-30 17:38 UTC, crysman approved these changes
cajk :heavy_check_mark:

2021-01-30 18:04 UTC, jankrcal commented
@ondraspribyla Pokud už to chceš pustit z hlavy, klidně udělám finální kontrolu a merge sám. Stačí napsat.

Spíš takto dávám možnost to naposledy vidět, než to půjde ven.

2021-01-30 18:14 UTC, ondraspribyla commented
Ok, merge a dataset necham na tobě, pouštím z hlavy...

Dne so 30. 1. 2021 19:04 uživatel jankrcal <notifications@github.com>
napsal:

> @ondraspribyla <https://github.com/ondraspribyla> Pokud už to chceš
> pustit z hlavy, klidně udělám finální kontrolu a merge sám. Stačí napsat.
>
> Spíš takto dávám možnost to naposledy vidět, než to půjde ven.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web-cz/pull/759#issuecomment-770253130>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EGAEIG4BYA25PELGJDS4RC3HANCNFSM4WZSTHIQ>
> .
>

2021-01-30 19:38 UTC, merged

2021-01-30 19:41 UTC, jankrcal commented
Hotovo, merged.

Kdybys měl crysmane během dalších dnů energii ještě ex post kouknout na moje poslední commity, budu rád.
Kdyby tam byl třeba nějakej hroznej překlep...

2021-01-30 20:33 UTC, crysman reviewed
cajk :+1: