Explainery (cz)
faktaoklimatu/web-cz pull request #766
Opened 2021-02-12 08:52 UTC by jankrcal

Úpravy ve web-cz, související se zveřejněním prvních (dvou) explainerů.

2021-02-12 08:53 UTC, jankrcal commented
Martine, prosím o technické review, je to můj první PR napříč dvěma repozitáři.

2021-02-12 08:57 UTC, jankrcal commented
(Matěji, přidávám Tě jako volitelného recenzenta, víc očí víc vidí)

2021-02-12 20:08 UTC, mukrop requested changes
Presiel som. Bolo by fajn, aby ste si viaceri nainstalovali do editora aspon spell check, pride mi divne, ked kontrola posledneho developera pred merge vidi chyby v spell checku :-).
* Ten text uz je v dvoch pripadoch ready na publikovanie?
* Na ten green deal budeme chciet feedback od niekoho externeho? Lebo takto je zverejneny, ale nie je doklikatelny. Korektny sposob rozpracovanej (nezverejnenej!) prace je nastavit `published: false` v hlavicke (co by malo automaticky stranku vyradit aj so sitemapy). Do buducna na feedback externistov planujem flexibilny devel build na subdomene.
* Inak ten system `| except sitemap: false` sa mi dost nepaci, bude viest ku chybam, ze sa na to niekde zabudne, Silno preferujem taketo veci nerobit a radsej ten posledny explainer dat neverejny (a na pripadny feedback ho poslat vo forme PDF, kedze to uz bude feedback na obsah).
* Vyroba cementu ma uplne na spodu medzi zdrojmi naked URLs. To, prosim nerobme, dajte tam aspon enjaky kratky text odkazu (co to vlastne je).
* Obrazky su jazykovo zavisle (patria k obsahu), prosim presunut do `assets-local`.
* Prekryv s nadpisom cez nahladovy obrazok explaineru nie je to prave, ale myslim, ze je zbytocne to teraz vymyslat, upravime to casom.

2021-02-12 20:09 UTC, mukrop commented
A este prosim pozri, co je ta Ondrasova vetva s upravami explainerov, nech sa to da dokopy idealne.

2021-02-14 19:47 UTC, jankrcal commented
Diky za recenzi! Ja jsem ty texty ted vubec necetl, myslel jsem, ze je to hotovy a nevenoval jsem tomu pozornost, omlouvam se :)

Github mi ukazuje Conflicting files: web-core. Nevim, jak to opravit. Poradis prosim, Martine?
(lokalne zadny konflikt nevidim)

Zapracoval jsem pripominky:
- presunuti obrazku do assets-local,
- odpublikovani zelene dohody,
- odstraneni filtru sitemap,
- opraveny naked URLs.

@ondraspribyla Jaky je prosim stav textu dychani, nezda se to byt ready na zverejneni. Krome toho mas otevrenou vetev https://github.com/faktaoklimatu/web-cz/compare/Upravy-explaineru, kde pridavas FIXME do cementu. Muzes se na to prosim podivat?

Jinak ja mam jeste dost touhu udelat zmensovani cover images, aby se do nahledu boxu pouzival mensi. Ale to muzu udelat v pozdejsim PR, pokud bychom toto uz meli ready.

2021-02-14 20:09 UTC, jankrcal commented
> Github mi ukazuje Conflicting files: web-core. Nevim, jak to opravit. Poradis prosim, Martine?
Ach, už to chápu. Samozřejmě. Normálně to potřebuje rebase oproti master. Jen mě zmátlo (a přijde mi nešikovný), že takový triviální konflikt nejde řešit z webového rozhraní.

2021-02-14 20:38 UTC, protivinsky commented
Pročetl jsem cement a udělal pár drobných textových oprav.

Jsem trochu zmatený z toho mého druhého commitu, to jsem neplánoval. Vypadá to, že jsme akorát upravovali větev zároveň s Jéňou a tím pádem jsem musel do své mergnout jeho změny (jinak byl můj push rejected, musel jsem prvně pullnout)? Jen se ujišťuji, že tím nic nerozbíjím?

2021-02-14 21:09 UTC, jankrcal commented
Díky!

K správě gitu používáš nějaké klikátko? Mně takové merge commits někdy udělá VS Code...

Jinak mi to přijde neškodné (kromě trochu nepřehledného logu).

2021-02-15 06:39 UTC, jankrcal commented
Udělal jsem rebase a vyřešil konflikty. Uviděl jsem, že už jsi Martine obrázky do assets-local přesunul na master. 

Trochu preferuju svoje řešení, kde cover i figures jsou nevázané na explainers (protože cover obrázky můžeme snadno využít i na jiné layouty a figures by se klidně hned mohly objevit v doprovodných textech infografik, či jinde). Ale nemám příliš silný názor.

2021-02-15 19:41 UTC, closed without merging