Preview otepleni koncentrace
faktaoklimatu/web-cz pull request #816
Opened 2021-04-15 16:03 UTC by ondraspribyla

Hotové texty, zbývá korektura a technické dokončení sazby: 

- [ ] jedno FIXME v textu ke grafice - sazba v pokračujícím odstavci...

Další issue v budoucnu, které bych rád vyřešil, je že v explaineru jsou v textu obrázky, které by bylo fajn mít možnost rozkliknout a zvětšit. Jinak řečeno, u obrázků, které jsou přidávány formou

 {% include figure.html
    name="cs-souvislost-koncentrace-oteplovani.svg"
    alt="Souvislost mezi koncentracemi CO2 a oteplováním"
%}

by bylo skvělé dodělat rozklikávání.  

Děkuju všem za spolupráci,  @mgrabovsky za přidání možnosti psát rovnice... bude z toho reportáž v rozhlase a články na irozhlas a snad i Deník N.

2021-04-15 16:06 UTC, ondraspribyla commented
... a teď Kristi sedící vedle mě říká, že ještě potřebuje opravit nějaké TYPO v grafice... tak to je v rámci dokončovacích prací.

2021-04-15 17:37 UTC, Jirka-tisnov commented
Nevím, jestli stihnu zítra, takže reálně spíš až počátkem týdne. Ale pokusím se :-)

2021-04-15 18:55 UTC, ondraspribyla commented
Stačí začátkem týdne. Jen já jsem to potřeboval mít z krku, abych mohl
řešit další věci... (hlavně ty prezentace a meetingy, ale taky české
lesy...)

O.

On Thu, 15 Apr 2021 at 19:37, Jirka Lněnička ***@***.***>
wrote:

> Nevím, jestli stihnu zítra, takže reálně spíš až počátkem týdne. Ale
> pokusím se :-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web-cz/pull/816#issuecomment-820609684>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EE6WO7UDZDPP4G2JBTTI4P45ANCNFSM427ZNB7A>
> .
>

2021-04-15 19:21 UTC, Jirka-tisnov commented
Deal. Můžeš se spolehnout. Držím palce!

2021-04-22 16:24 UTC, ondraspribyla commented
Na čem se tahle práce zasekla?

2021-04-22 16:58 UTC, mukrop commented
Na tom, ze mam inu pracu do skoly (opravy domacich uloh, dizertacka).

2021-04-23 08:10 UTC, mukrop requested changes
Nieco som presiel, este mi par veci zostava. Postrehy zatial:
* [ ] Prosim doplnte aktualitu.
* Obrazky nahravajte idealne uz v zmensenej/orezanej variante. Bol tam `-old` subor v povodnej velkosti. Tym, ze git drzi celu historiu budeme tieto povodne velkosti vzdy s celym repom stahovat (jeden nevadi, ale ak to budeme robit bezne, obrovsky tym zvacsime repo).
* @Jirka-tisnov v ramci jasnejsieho workflow: Prosim, ked bude tvoja praca hotova, tak pridaj do Pull requestu "Approve" (na poslednom tabe "Files changed" je zelene tlacitko, kde mozes dat celkovy review a "Approve" je jedna z moznosti). Potom prehladnejsie vidno, kto to uz presiel (a ci uz cele).
* Suvisiaca: @Jirka-tisnov, este tam mas nejaku pracu, alebo za eba hotovo?
* Redirect z kratsieho URL na explainer som zrusil, nemavame ich. Tym padom som upravil slug na rovnaky, ako ma infografika.

2021-04-23 10:04 UTC, Jirka-tisnov commented
- Aktualitu dopíšu, snad ještě dnes.
- Na "Approve" zkusím příště pamatovat :-)
- Text k infografice po zapracování změn za mě OK, k explaineru viz můj comment: 

Text po první korektuře (ještě to budu potřebovat projít jednou, až to někdo schválí). Bylo tam dost změn – pro příště poprosím o možnost projít to nejprve v googledocs, kde se mi to líp upravuje a dělají se mi tam snáz větší úpravy textu a formulací. V GITu bych to rád už jen finálně ladil (překlepy apod.) a nedělal příliš mnoho změn. 
A omlouvám se za svou laickou nevědomost, ale části Lineární, nebo logaritmická závislost pořád úplně nerozumím – mezi poslední větou toho odstavce a jeho zbytkem mi chybí jasný spoj, který tam autor nejspíš vidí, ale já ne. Přestože chápu, co je aproximace, lineární a logaritmický, celá tato část pro mě zůstává s otazníkem. A celý ten explainer je pořád dost hutný a vyžaduje pro mě velké soustředění, ale OK. Bavili jsme se na toto téma i s Kristi, že má podobný problém – což je asi naše omezení, ale přece jen máme já a ona blíž k typickému čtenáři čili beru to jako připomínku, která je relevantní ;-)

Víc tomu asi už tento týden nedám, ale zkraje příštího bych mohl dotáhnout tu korekturu.

2021-04-23 10:06 UTC, Jirka-tisnov approved these changes
Za mě OK :-)

2021-05-01 09:03 UTC, mukrop approved these changes

2021-05-01 10:45 UTC, merged