Update infografiky uhelného phase-outu
faktaoklimatu/web-cz pull request #821
Opened 2021-04-29 20:13 UTC by mgrabovsky

Prosím o kontrolu textu a grafiky.

Resolves #663

2021-04-29 20:14 UTC, mgrabovsky commented
Ještě jsem si všiml, že PDFko nějak nabobtnalo. To budeme řešit zítra.

2021-04-30 11:14 UTC, jankrcal requested changes
Kromě odkazu na tabulku za mě dobrý, díky za práci!

(časem bychom mohli aktualizovat data o výrobě za rok 2020, ale to možná počká ještě rok a uděláme rovnou 2021 :)

2021-04-30 13:44 UTC, mgrabovsky commented
Aktualizoval jsem odkaz na dataset.

2021-04-30 17:50 UTC, jankrcal approved these changes

2021-04-30 17:50 UTC, jankrcal commented
Díky, dataset jsem přesunul do finální destinace a zveřejnil.

2021-05-01 09:36 UTC, mukrop approved these changes
Za mna tiez OK, dik.

2021-05-01 09:36 UTC, merged