doplněna UK, lepší zdroje a data aktualizací zdrojů
faktaoklimatu/web-cz pull request #859
Opened 2021-06-07 10:35 UTC by mukrop

Vytvaram PR za Fila, aby pripadne problemy a nezrovnalosti dali diskutovat priamo pri zmenach kodu,

2021-06-07 10:46 UTC, mukrop commented
@Filip-Kessner, pises, ze sa rozbilo radenie, ale u mna to vyzera OK. V com je presne problem?
Divajuc sa do kodu, radenie sa nerobi automaticky, ale prebera sa poradie, ktore je v strukture `items`.

Za mna je to takto OK (z technickeho pohladu), ale pre istotu sa pytam, ci tam nie je nieco, co som si nevsimol.

Chce to este obsahove review. @ondraspribyla, pozries sa na to? Dostupne online na https://cz-fakta-o-klimatu--preview-update-reserse-zavazku-61zacett.web.app/studie/2021-reserse-zavazky-statu

2021-06-08 10:01 UTC, ondraspribyla commented
koukám na to a nevidím žádný problém. Británie je přidaná těsně pod EU27, což je podle mě logické místo... Takže good job! approved.

2021-06-08 10:04 UTC, ondraspribyla requested changes
Aha, takuž vidím, co jsem v preview neviděl: nezobrazuje se datum aktualizace  - tedy v kódu je kategorie "aktualizováno" ale ve zobrazené tabulce tato kategorie chybí...

2021-06-08 10:37 UTC, mukrop commented
@ondraspribyla je to ako "hover" pri podrzani mysi na tlacitku, tj. na telefone to moc nebude vidiet. Takto to vymyslel Fil. Je to nenapadne, ale popravde trochu neviem, ako inak to tam dostat. Nejake napady? Myslis, ze ma zmysel davat tomu samostatny stlpec?

2021-06-08 10:57 UTC, ondraspribyla commented
Ok, jako řešení se mi to líbí - když o tom vím - tedy asi jediný požadavek
z mé strany je napsat do úvodního textu poznámku, že data se v této době
docela mění a proto datum aktualizace můžete videta jko hoover text nad
linky ( formulaci bude třeba vymyslet lepší, nevím třeba jak se hoover text
překládá do češtiny...)


On Tue, 8 Jun 2021 at 12:37, Martin Ukrop ***@***.***> wrote:

> @ondraspribyla <https://github.com/ondraspribyla> je to ako "hover" pri
> podrzani mysi na tlacitku, tj. na telefone to moc nebude vidiet. Takto to
> vymyslel Fil. Je to nenapadne, ale popravde trochu neviem, ako inak to tam
> dostat. Nejake napady? Myslis, ze ma zmysel davat tomu samostatny stlpec?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web-cz/pull/859#issuecomment-856654139>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2ECNLDFYOIBCCWWYX43TRXXILANCNFSM46HL2PJQ>
> .
>

2021-06-09 09:47 UTC, mukrop commented
Super, dik. @Filip-Kessner, doplnis tam prosim text, ktory spomina Ondras?

2021-06-10 16:41 UTC, mukrop commented
Este som opravil styl tlacitok (pri detailnejsom preskumani boli naozaj trochu porozhadzovane).

2021-06-10 16:41 UTC, merged