Doplnění tagu příroda
faktaoklimatu/web-cz pull request #873
Opened 2021-06-14 08:02 UTC by protivinsky

Při přidání rešerše lesů ČR jsme zavedli novou kategorii příroda (ekosystémy, biodiverzita, krajina). Doplňuji tento tag k relevantnímu stávajícímu obsahu.

@mukrop prosím o review + merge, díky.

2021-06-14 08:25 UTC, mukrop requested changes
Dobre zmeny, dik za prejdenie obsahu spatne.

* [ ] Len na usitenie, naozaj to dame len na body zlomu 1? Mas tam aj popis "krajina", tak by som zvazoval dat to na vsetky.
* [x] Uz som to chcel napisat k tomu PR, ktory tuto kategoriu zavadzal, ale mergli ste ho, tak pisem sem: Ten dlhy nazov je prilis dlhy, menu v navigacnej liste na mobiloch uz to nezvlada, vid screenshot. Nemohli by ste vyhodit jedno slovo? (Kludne "biodiverzita", lebo je dlhe a podla mna je to pod prirodou a ekosystemami).

![tmp](https://user-images.githubusercontent.com/1871676/121862057-bfff4500-ccfa-11eb-9f9b-f26f47b451e5.PNG)

2021-06-15 09:36 UTC, protivinsky commented
diky za kontrolu - vyhodil jsem biodiverzitu, i kdyz je to skoda. jeji vyznam je dost odlisny oproti ostatnim kategoriim, i kdyz zatim toho k ni specificky prilis nemame ani neplanujeme.
ty zbyle grafiky body zlomu mi k tomu tolik nesednou, zatim bych je tam nedaval.

2021-06-15 10:05 UTC, ondraspribyla commented
Ok, souhlas...

O.

On Tue, 15 Jun 2021 at 11:36, Tomas Protivinsky ***@***.***>
wrote:

> diky za kontrolu - vyhodil jsem biodiverzitu, i kdyz je to skoda. jeji
> vyznam je dost odlisny oproti ostatnim kategoriim, i kdyz zatim toho k ni
> specificky prilis nemame ani neplanujeme.
> ty zbyle grafiky body zlomu mi k tomu tolik nesednou, zatim bych je tam
> nedaval.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web-cz/pull/873#issuecomment-861348190>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEED2EB5CT3HZZ325HMB4ATTS4NK7ANCNFSM46UWUKWQ>
> .
>

2021-06-16 09:06 UTC, mukrop approved these changes
Dik za opravu.

2021-06-16 09:06 UTC, merged