[WiP] Cllimate finance explainer
faktaoklimatu/web-cz pull request #942
Opened 2021-11-05 14:50 UTC by protivinsky

Ať se dá komentovat.

2021-11-05 15:21 UTC, moraval reviewed
Chybi mi doprojit "Dari se zavazek naplnovat" A "Kdo jsou pris..."

2021-11-05 15:21 UTC, moraval commented on _explainers/klimaticke-finance.md
> +Jako rozvinutá země a součást Evropské unie do klimatických financí přispíváme také, a to jak multilaterálními, tak bilaterálními smlouvami. V roce 2018 se jednalo o 185 milionů korun a **ve srovnání
Tohle je matouci, nevim co se tim snazime rict:
> Příspěvky vycházející z bilaterálních vztahů míří z ČR k některým balkánským státům a dalším zemím (např. Etiopie nebo Kambodža), prostřednictvím multilaterárních fondů jsme v roce 2018 přispěli 26 miliard korun. OECD ve své databázi rozvojové pomoci související s klimatem uvádí vyšší částku 240 milionů korun[^9], ani tato však zdaleka neodpovídá výši závazku rozvinutých zemí.

2021-11-05 15:21 UTC, moraval commented on _explainers/klimaticke-finance.md
> +**Nejvíce do klimatických financí přispívá Japonsko, Německo a Francie**, tyto země zároveň přispívaji přibližně dvojnásobek oproti tomu, kolik by odpovídalo poměru podle výše jejich HDP. Německo při
```suggestion
**Nejvíce do klimatických financí přispívá Japonsko, Německo a Francie**, tyto země zároveň přispívaji přibližně dvojnásobek oproti tomu, kolik by odpovídalo poměru podle výše jejich HDP. Německo přispívá přibližně polovinu částky formou grantů a polovinu formou půjček, oproti tomu u Japonska a Francie půjčky výrazně převažují. USA sice poskytuje většinu financí formou grantu, ale celková částka je velice nízká. Pro dosažení férového podílu podle HDP by USA muselo navýšit své příspěvky na šestinásobek, zároveň USA také patří mezi největší světové znečišťovatele, a to jak v absolutních číslech, tak i při přepočtu na obyvatele. **Většina ostatních rozvinutých zemí také přispívá méně, než kolik by odpovídalo jejich férovému podílu.**
```

2021-11-05 15:21 UTC, moraval commented on _explainers/klimaticke-finance.md
> +Tento závazek podpory od rozvinutých k rozvojovým státům je nezbytným krokem pro naplnění klimatických cílů a pro posílení důvěry v globální spolupráci, zároveň však dosud naplňován není, přislíbená
```suggestion
Tento závazek podpory od rozvinutých k rozvojovým státům je nezbytným krokem pro naplnění klimatických cílů a pro posílení důvěry v globální spolupráci. Zároveň však dosud naplňován není a ani přislíbená částka není dostatečná pro realizaci potřebných opatření a pro transformaci hospodářství v rozvíjejících se zemích, v neposlední řadě závazek ani nezohledňuje snižující se kupní sílu dolaru v důsledku inflace.
```

2021-11-05 15:21 UTC, moraval commented on _explainers/klimaticke-finance.md
> +Rozvojové země mají méně vlastních prostředků a složitější přístup k půjčkám, proto jsou pro ně investice pomáhající zabránit dopadům klimatické změny či se na ně adaptovat složité. Tyto země usilují
```suggestion
Rozvojové země mají méně vlastních prostředků a složitější přístup k půjčkám, proto je pro ně složité získat zdroje na investice pro zmenšování či adaptaci na klimatické změny. Tyto země ale zárověň potřebují hospodářský růst, který by jim pomohl vymýtit chudobu a zlepšit životní úroveň jejich obyvatel. **Nejen pro ně, ale i pro nás - obyvatele rozvinutých a bohatých zemí - je klíčové, aby tento růst byl umožněn pomocí čistých technologií.** Pokud by dnešní rozvojové země při svém hospodářském růstu vypouštěly skleníkové plyny v takové míře, jako rozvinuté země vypouštěly při svém růstu v minulosti, pak by dosažení klimatických cílů nebylo možné. Rozvojové země zároveň často patří k těm nejvíce zasaženým klimatickou změnou, část klimatických financí je proto určena i na <glossary id="adaptace">adaptační opatření</glossary>. 
```

2021-11-05 15:21 UTC, moraval commented on _explainers/klimaticke-finance.md
> +Klimatické finance umožňující rozvojovým zemím investice do čistých technologií jsou velice důležité pro všechny země, nikoli pouze pro jejich příjemce. Rozvojové země často patří k těm nejvíce zasaž
```suggestion
Nejde však pouze o finanční přínos, **klimatické finance zároveň podporují snahy těchto zemí s klimatickou změnou něco dělat a posilují důvěru ve spolupráci na globální úrovni.**
```

2021-11-05 15:37 UTC, moraval commented on _explainers/klimaticke-finance.md
> +Jako rozvinutá země a součást Evropské unie do klimatických financí přispíváme také, a to jak multilaterálními, tak bilaterálními smlouvami. V roce 2018 se jednalo o 185 milionů korun a **ve srovnání
Ha, mne se tu ztratil koment.. :)
Tehle casti vubec nerozumim:

> Příspěvky vycházející z bilaterálních vztahů míří z ČR k některým balkánským státům a dalším zemím (např. Etiopie nebo Kambodža), prostřednictvím multilaterárních fondů jsme v roce 2018 přispěli 26 miliard korun. OECD ve své databázi rozvojové pomoci související s klimatem uvádí vyšší částku 240 milionů korun[^9], ani tato však zdaleka neodpovídá výši závazku rozvinutých zemí.

2021-11-05 17:39 UTC, ondraspribyla commented
Pěkně jste s tím pohli! Četl jsem teď text na preview, a působí na mě o řád uceleněji. Myslím, že jeidná kapitola, kde bych stál o trochu uvedení je "Co všechno spadá do..." - Uvítal bych odstaveček úvodu ve stylu "Když jste příjemce, je rozdíl, když dostanete půjčku nebo grant, nebo jestli ve vaší zemi proste cizí firma/stát něco zainvestuje... Stejně tak když jste investor, chcete mít buď zisk z investice, nebo aspoň garanci, že to příjemce nerozfrcá ... "

2021-11-05 17:45 UTC, moraval commented on _explainers/klimaticke-finance.md
> +Celková částka sice postupně stoupá, nicméně **v roce 2020 závazek naplněn nebyl** (přesná čísla pro tento rok zatím nejsou k dispozici, ale vzhledem k tomu, že **o rok dříve bylo plnění přibližně 80
```suggestion
Celková částka sice postupně stoupá, nicméně **v roce 2020 závazek naplněn nebyl** (přesná čísla pro tento rok zatím nejsou k dispozici, ale vzhledem k tomu, že **o rok dříve bylo plnění přibližně 80 % – 79,6 miliard dolarů** – z původně zamýšlené částky, není příliš pravděpodobné, že by bylo částky dosaženo)[^2]. To má velký vliv na důvěru rozvojových států k těm rozvinutým a je to jedno z hlavních témat klimatické konference COP 26 v Glasgow. Závazek bude pravděpodobně prodloužen do roku 2025, přičemž diskuze se povedou ohledně jeho velikosti od roku 2025 dál. Velká Británie jako předsedající země vydala nový plán dosažení závazků, který počítá s tím, že by k jeho splnění mělo dojít v roce 2023[^8]. Posuzování naplnění závazku je komplikováno také nejednoznačným vymezením, co klimatické finance přesně zahrnují.
```

2021-11-05 17:47 UTC, moraval commented on _explainers/klimaticke-finance.md
> +Definice klimatických financí je velmi široká – patří sem **finance z bilaterálních i multilaterálních zdrojů, ale například i soukromé zdroje** (ty mohou být započítány do celkového součtu, pokud by
Jsme si teda jisti temi procenty? (21%, 71%) Ja myslela, ze je nakonec chceme vynechat - nebo jsme to overili?

2021-11-05 18:32 UTC, protivinsky commented on _explainers/klimaticke-finance.md
> +Definice klimatických financí je velmi široká – patří sem **finance z bilaterálních i multilaterálních zdrojů, ale například i soukromé zdroje** (ty mohou být započítány do celkového součtu, pokud by
jo, je to převzaté z té OECD zprávy

2021-11-05 18:32 UTC, protivinsky commented on _explainers/klimaticke-finance.md
> +Jako rozvinutá země a součást Evropské unie do klimatických financí přispíváme také, a to jak multilaterálními, tak bilaterálními smlouvami. V roce 2018 se jednalo o 185 milionů korun a **ve srovnání
ok, opravil jsem a zjednodusil

2021-11-05 18:36 UTC, protivinsky commented on _explainers/klimaticke-finance.md
> +Klimatické finance umožňující rozvojovým zemím investice do čistých technologií jsou velice důležité pro všechny země, nikoli pouze pro jejich příjemce. Rozvojové země často patří k těm nejvíce zasaž
to není opakování, má to jiný význam - ale rozumím, že ohledně toho musím být explicitnější

2021-11-05 18:38 UTC, protivinsky commented on _explainers/klimaticke-finance.md
> +Klimatické finance umožňující rozvojovým zemím investice do čistých technologií jsou velice důležité pro všechny země, nikoli pouze pro jejich příjemce. Rozvojové země často patří k těm nejvíce zasaž
aha, tys to prehodila nahoru, nevsiml jsem si predtim. promyslim to.

2021-11-08 16:08 UTC, protivinsky commented
@mukrop Ondras mi to odsouhlasil na slacku, zbyva technicke review a merge. Diky.

2021-11-08 16:11 UTC, mukrop commented
Tak to bolo naraz, @Jirka-tisnov, @protivinsky to v medzicase napisal sem a oznacil.

@protivinsky este prosim o douzavretie pripomienok od @moraval vyssie v diskusii. Ak su doriesene, tak klik "resolve" (ja sa v obsahu nevyznam, ale pomaha mi to byt si isty, ze obsahovo s to niekto doriesil, lebo musel vedome kliknut na resolve). Pripadne approve od @moraval budem interpretovat rovnako (ze je to znova prejdene a vsetko doriesene).

Technicke review a merge az zajtra, ak na to nie je extra dovod tlacit.

2021-11-08 16:16 UTC, moraval approved these changes

2021-11-08 16:28 UTC, protivinsky commented
jo jo, prochazel jsem to, vse je resolved.

2021-11-09 08:47 UTC, mukrop requested changes
Super, mam len jednu drobnost: Mas tam zakomentovany obrazok `prijemci-podle-regionu`, ktory v suboroch nie je. Aky je s nim plan? Ak ani nebude, komentar prosim vyhodit (mozem urobit, ale potrebujem to potvrdit). Ak je v plane, tak preferujem komentar aj tak vyhodit a zalozit si na to issue (kde is mozes poznacit zdroj a tak),

2021-11-09 13:28 UTC, mukrop approved these changes
Zakomentovany obrazok som po konzultacii s @ondraspribyla zmazal a presunul ako dotaz do #945.

2021-11-09 13:38 UTC, merged